### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by EVMOS02** [stormxio/crowdsale#11]
Hello please how can I change my email ?

**Comment by Brovmos** [comment]
I am having the same issue,I misplaced my phone and I think someone else access and hack my email I've not been able to access the email and even stole some available balance on my wallet,tho my staking is still there but I've not been able to access the staking because of the email I registered with

**Comment by calvinh8** [comment]
For account support, please reach out to us at support@stormx.io.

**Comment by Brovmos** [comment]
> For account support, please reach out to us at support@stormx.io.

I've been texting the support but my issues hasn't resolved.. almost a month now
